version: '3.8'

services:
  backend:
    image: pashamwad123/expense-tracker-backend:latest
    container_name: expense-tracker-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
    networks:
      - expense-tracker-network
    restart: unless-stopped

  frontend:
    image: pashamwad123/expense-tracker-frontend:latest
    container_name: expense-tracker-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - expense-tracker-network
    depends_on:
      - backend
    restart: unless-stopped

networks:
  expense-tracker-network:
    driver: bridge