---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-tracker-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-tracker-backend
  template:
    metadata:
      labels:
        app: expense-tracker-backend
    spec:
      containers:
      - name: backend
        image: pashamwad123/expense-tracker-backend:latest
        imagePullPolicy: Always # Changed to pull from Docker Hub
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: LoadBalancer # K3s will automatically expose this on the AWS EC2 IP
  selector:
    app: expense-tracker-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-tracker-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-tracker-frontend
  template:
    metadata:
      labels:
        app: expense-tracker-frontend
    spec:
      containers:
      - name: frontend
        image: pashamwad123/expense-tracker-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: expense-tracker-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
